CREATE TABLE usuario (
id INT PRIMARY KEY AUTO_INCREMENT,
login VARCHAR (255) NOT NULL UNIQUE,
senha VARCHAR (255) NOT NULL
);

CREATE TABLE eventos (
id INT PRIMARY KEY AUTO_INCREMENT,
nome_evento VARCHAR (255) NOT NULL,
data_evento DATE NOT NULL,
hora_evento TIME NOT NULL,
descricao TEXT NOT NULL
);


